name: Link Checker

on:
  schedule:
    - cron: '0 0 * * 0' # 每周日UTC 0点运行
  workflow_dispatch:

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-verbose-mode: 'yes'
          check-modified-files-only: 'no'
